version: "3.8"

services:
  docs:
    build:
        context: .
        dockerfile: ./src/docs/Dockerfile
    image: docs:0.1.0
    volumes:
      - ./src/docs:/code
      - core-venv:/code/venv
      - core-tox:/code/.tox
    command:
      - "sleep"
      - "infinity"
    restart: unless-stopped

volumes:
  core-venv:
    external: false
    name: "docs-venv"

  core-tox:
    external: false
    name: "docs-tox"
