site_name: AC Documentation
site_author: Alexandre CUFFEL
copyright: 2020 - 2021 © AC
site_url: https://docs.acuffel.com/
repo_name: ACuffel/docs
repo_url: https://github.com/acuffel/docs.git
edit_uri: 'edit/main/src/'
docs_dir: 'src'
site_dir: 'docs'
theme:
  language: en
  name: material
  custom_dir: overrides/material
  palette:
    primary: deep purple
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: images/favicon.png
  # logo: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - search:
      lang:
        - fr
        - en
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acuffel
      name: Acuffel docs on GitHub
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
